name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  test-project-creation:
    name: Test project creation (min_python=${{ matrix.min_python }}, docs=${{ matrix.docs }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        min_python: ["3.11", "3.12", "3.13"]
        docs: [true, false]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - uses: astral-sh/setup-uv@v5
      - name: Install copier
        run: pip install copier
      - name: Create new project
        run: |
          copier copy \
            -d project_name=test-project \
            -d project_short_description="A great package." \
            -d python_name=test_project \
            -d full_name=gh_actions \
            -d email=foo@example.com \
            -d license=MIT \
            -d min_python_version=${{ matrix.min_python }} \
            -d include_docs=${{ matrix.docs }} \
            -d org=gh_actions \
            -d url=https://github.com/gh_actions/test-project \
            --vcs-ref HEAD \
            . my-project
      - name: Verify project
        run: |
          cd my-project
          git config --global user.email "foo@example.com"
          git config --global user.name "gh_actions"
          git init
          git add .
          git commit -m "Initial commit"
          uv sync
          uv run pytest || true
          uv run ruff check .
          uv run ruff format --check .
