name: Test Template Instance

on:
  pull_request:
    branches:
      - main


jobs:
  Creation:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install Dependencies
        run: |
          pip install copier pre-commit
      - name: Create new project
        run: |
          copier copy \
            -d project_name=test \
            -d org=gh_actions \
            -d full_name=gh_actions \
            -d email=foo@example.com \
            -d license=BSD \
            -d backend=setuptools \
            -d typing=strict \
            -d coc=our_coc \
            project_template instance
      - name: linting
        run: |
          cd instance
          cat .pre-commit-config.yaml
          pre-commit run --all-files
      - name: Check project installs (with -e)
        run: pip install -e .
